name: aloha
description: Applikation für Welle Ev.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  camera: ^0.8.1
  image_picker: ^0.8.4+1
  path_provider: ^2.0.1
  tflite_flutter: ^0.8.0
  tflite_flutter_helper:
  material_design_icons_flutter: ^5.0.5955-rc.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  meta: ^1.3.0
  collection: ^1.15.0
  quiver: ^3.0.1
  shimmer: ^2.0.0
  flutter_local_notifications: ^8.2.0
  rxdart: ^0.27.0
  provider:
  intl: ^0.17.0
  google_fonts: ^2.1.0
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  flutter_platform_widgets: ^1.9.5
  page_view_indicators: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: BrueckeIcons
      fonts:
        - asset: icons/BrueckeIcons.ttf
    - family: Roboto
      fonts:
        - asset: font/Roboto-Black.ttf
        - asset: font/Roboto-BlackItalic.ttf
        - asset: font/Roboto-Bold.ttf
        - asset: font/Roboto-BoldItalic.ttf
        - asset: font/Roboto-Italic.ttf
        - asset: font/Roboto-Light.ttf
        - asset: font/Roboto-Medium.ttf
        - asset: font/Roboto-MediumItalic.ttf
        - asset: font/Roboto-Regular.ttf
        - asset: font/Roboto-Thin.ttf