/// Flutter icons BrueckeIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BrueckeIcons
///      fonts:
///       - asset: fonts/BrueckeIcons.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class BrueckeIcons {
  BrueckeIcons._();

  static const _kFontFam = 'BrueckeIcons';
  static const String? _kFontPkg = null;

  static const IconData glass =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer_1 =
      IconData(0xf0fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wine_glass =
      IconData(0xf4e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wine_glass_alt =
      IconData(0xf5ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wine_bottle =
      IconData(0xf72f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
